# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0a56d943e6ee1468acb0831d226c004642a6989e9c91a9105807a26b91810e71aed36b9fac510f498b42ddb71549f558ad8c40c4196049529f331e7393880d8

test:
  secret_key_base: a56c8f98891dcebffcfbd621b8c4262d1891c60caab38c9496866a9e5d6b879163420d3fa30b1254503a473aa271186da744bc4a2f45469d1cd4c45c23f5f835

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
